### ISSUE TITLE
Прилетел бан на киви за то что не передавал реферальные ссылки

### ISSUE THREAD

**Issue by lionead** [WhiteApfel/pyQiwiP2P#14]
Неожиданно прилетел бан из-за "странных действий". После разборок с тп получил разбан, они сказали, что если реферальная ссылка передаваться не будет, бан будет снова.

Можно добавить в bill реферальную ссылку эту? В документации у них это где-то должно лежать

**Comment by lionead** [comment]
`Здравствуйте!

Уважаемый клиент, ваш QIWI кошелек разблокирован.
Приносим вам извинения за доставленные неудобства.



Если реферальные ссылки не будут передаваться, кошелек будет заблокирован снова.

Благодарим за обращение!`
Вот их ответ

**Comment by WhiteApfel** [comment]
В документации ничего нет по этому поводу. Позвонил на горячую линию, там сказали, что каждый случай рассматривается отдельно и не могут меня консультировать. Написал в чатик, жду ответа. 

Если кинешь свой ник/email, с которого писал, буду особенно благодарен

**Comment by lionead** [comment]
lionia058@gmail.com

**Comment by lionead** [comment]
Может быть это ссылка перенаправления в конце платежа? Просто блин страшно на киви оплату переходить, уже переписал оплату в боте на крипту

**Comment by WhiteApfel** [comment]
Короче, порешали. Готовься держать челюсть. Теперь обязательно использовать сайт-прокладку, ибо они принимают исключительно если есть заголовок [Refer](https://developer.mozilla.org/ru/docs/Web/HTTP/Headers/Referer). Они разместили инфу вот тут: https://qiwi.com/support/products/p2p/referalnie_ssylki

Почему тебе не дали ссылку -- вопрос. Почему назвали это не заголовком, а реферальной ссылкой -- вопрос.

**Comment by WhiteApfel** [comment]
В течение пары дней постараюсь выкатить сервис для промежуточных ссылок, чтобы не напрягать юзеров.

**Comment by WhiteApfel** [comment]
Моя позиция по этому поводу и тред. 

https://twitter.com/WhiteApfel/status/1402885002073886725

**Comment by lionead** [comment]
Оке, жду
Ну и комедия...

**Comment by WhiteApfel** [comment]
Короче, подменивать Referer -- та ещё срань. Хз, как поможет от блокировок, но как я понял, они проверяют именно наличие...

**Comment by lionead** [comment]
А можно ли сделать как параметр для кассы/счёта? Можно же передавать ссылку на бота

**Comment by lionead** [comment]
Впринципе, если будет что-то, я готов тестить, после любого пополнения перегонять на тинькофф

**Comment by WhiteApfel** [comment]
Ну типа.... `python -m pip install pyQiwiP2P==2.0a3`

Добавил к объекту Bill атрибут alt_url, который проксирует открытия по дефолту через qp2p.0708.su. Можно развернуть контейнер для своего домена. У контейнера 3600 порт за сервер внутренний отвечает.

**Comment by WhiteApfel** [comment]
И версия `python -m pip install pip install pyQiwiP2P==2.0a4`

**Comment by lionead** [comment]
Туда можно свою ссылку передать, верно?

**Comment by WhiteApfel** [comment]
Куда? 

Referer образуется так:
1) Клиент жмёт на ссылку
2) Открывается страница
3) Происходит перенаправление на страницу оплаты средствами браузера
4) Браузер запоминает, с какой страницы он перешёл и сохраняет эту инфу в referer. 

Любую ссылку туда поставить не получится. Должен быть рабочий сайт

**Comment by WhiteApfel** [comment]
Рабочий сайт, который откроет страницу оплаты

**Comment by lionead** [comment]
ааа, понял

**Comment by lionead** [comment]
тележка есть? хочу обсудить один момент

**Comment by WhiteApfel** [comment]
Был вариант с использованием vk.com/away,php, который делает типа переход с VK, но он не работает, если человек не авторизован в ВК. А аналогичных штук я не нашёл. 

t.me/apfel
