### ISSUE TITLE
В файле __init__ на pypi нет AioQiwiP2P

### ISSUE THREAD

**Issue by GagikProger** [WhiteApfel/pyQiwiP2P#15]
Добрый день, я скачал установил из pypi библиотеку и там не было в __init__ файле from pyqiwip2p.AioQiwip2p import AioQiwiP2P . В гитхабе всё нормально

**Comment by WhiteApfel** [comment]
Пока что версия с асинхронным классом нестабильна, находится в альфе. https://pypi.org/project/pyQiwiP2P/2.0a10/
Ставится из pypi с указанием номера версии.
17 авг. 2021 г., 17:14 +0300, GagikProger ***@***.***>, написал (-а):
