### ISSUE TITLE
Нарушение нотации типов данных. 

### ISSUE THREAD

**Issue by Nikittttt** [WhiteApfel/pyQiwiP2P#33]
https://github.com/WhiteApfel/pyQiwiP2P/blob/101088853f80ae0fa758da5a304b72346bab9cee/p2proxy/server/proxy.py#L10 в качестве методов указывается строка, хотя в используемой библиотеке starlette https://github.com/encode/starlette/blob/5ee04ef9b1bc11dc14d299e6c855c9a3f7d5ff16/starlette/routing.py#L650 сказано что ожидается список из строк. Предположительно приводит к ошибке Method Not Allowed при работе.

**Comment by WhiteApfel** [comment]
Решено вместе с #34 в версии 2.0.4
