### ISSUE TITLE
Не тот объект

### ISSUE THREAD

**Issue by Nikittttt** [WhiteApfel/pyQiwiP2P#34]
https://github.com/WhiteApfel/pyQiwiP2P/blob/101088853f80ae0fa758da5a304b72346bab9cee/p2proxy/server/proxy.py#L11
в bill_uid принимаемом в функцию хранится объект  запроса, при этом нотация типов вводит в заблуждение говоря что там строка bill_uid, хотя саму строку можно взять в path_params у объекта запроса.

**Comment by WhiteApfel** [comment]
С момента написания этого кода, либа старлетте изменилась. Нет сил менять. Если будет PR -- оформлю в релиз

**Comment by Nikittttt** [comment]
В целом можно добавить в requirements старые версии. Ебсли руки дойдут, на выходных постараюсь залить свой фикс
