### ISSUE TITLE
KeyError: 'email'

### ISSUE THREAD

**Issue by json1c** [WhiteApfel/pyQiwiP2P#35]
Код:
`bill = await p2p.check(bill_id=bill_id)`

Traceback:
```
  File "/home/the_best_bot_in_the_world_yes/bot/handlers/payments.py", line 156, in check_invoice
    bill = await p2p.check(bill_id=bill_id)
  File "/usr/local/lib/python3.10/dist-packages/pyqiwip2p/AioQiwip2p.py", line 259, in check
    qiwi_response = Bill(qiwi_raw_response, self.alt)
  File "/usr/local/lib/python3.10/dist-packages/pyqiwip2p/p2p_types/responses.py", line 87, in __init__
    QiwiCustomer(json_data=self.r_json["customer"])
  File "/usr/local/lib/python3.10/dist-packages/pyqiwip2p/p2p_types/customer.py", line 50, in __init__
    self.email = json_data["email"]
KeyError: 'email'
```

В чём заключается суть проблемы и как её воспроизвести:

Создаём счёт через метод AioQiwiP2P.bill, оплачиваем, и вызываем метод AioQiwiP2P.check, естественно с bill_id, которое вернул нам первый метод. После чего ловим такую ошибку. При неоплаченном счёте никаких ошибок нет, но если он оплачен, то собственно видим то, что я описал. Похоже, киви что-то изменил в своём API, нужно обновить библиотеку под это.

**Comment by json1c** [comment]
Ошибка, кстати, вылезает только при оплате с кошелька Qiwi. Если оплачивать с карты, то её не будет.

**Comment by WhiteApfel** [comment]
Надо заменить на json_data.get("field_name", None) все три строчки в файле, из которого вызывается ошибка. Кидай pr

**Comment by json1c** [comment]
А сам не можешь поменять?


Ну ладно, сейчас.

**Comment by json1c** [comment]
кинул PR.

> json_data.get("field_name", None)

None необязательно указывать, потому что он является optional, то есть даже если его не передать, будет None

**Comment by WhiteApfel** [comment]
Исправлено в [версии 2.0.3](https://pypi.org/project/pyQiwiP2P/2.0.3/)

**Comment by qu0ta** [comment]
Подскажите, как решить проблему? Не понимаю(

**Comment by WhiteApfel** [comment]
@qu0ta, ну даже не знаю, может, обновить пакет, раз написано, что проблема исправлена в такой-то версии?
