### ISSUE TITLE
sha25

### ISSUE THREAD

**Issue by SUMER9999dev** [WhiteApfel/pyQiwiP2P#5]
https://github.com/WhiteApfel/pyQiwiP2P/blob/79b8b85aa0c078da8d54149ee8a3a21a3b5c7ba1/pyqiwip2p/notify/__init__.py#L57
https://github.com/WhiteApfel/pyQiwiP2P/blob/79b8b85aa0c078da8d54149ee8a3a21a3b5c7ba1/pyqiwip2p/notify/__init__.py#L65

измените на SHA256
как указано в документации p2p: https://developer.qiwi.com/ru/p2p-payments/#notifications_auth

**Comment by SUMER9999dev** [comment]
уже готовое исправление:
https://github.com/WhiteApfel/pyQiwiP2P/pull/6

**Comment by WhiteApfel** [comment]
Пяу ✨

**Comment by SUMER9999dev** [comment]
и скорее всего hmac тоже не будет работать, в hmac.new(key: bytes, text: bytes) желательно исправьте это тоже.

**Comment by SUMER9999dev** [comment]
![image](https://user-images.githubusercontent.com/59053498/114183336-3f177c00-994c-11eb-87bd-a44e75c58750.png)

**Comment by SUMER9999dev** [comment]
![image](https://user-images.githubusercontent.com/59053498/114183397-53f40f80-994c-11eb-93c7-e682ef6f8f7b.png)

**Comment by SUMER9999dev** [comment]
![image](https://user-images.githubusercontent.com/59053498/114183580-80a82700-994c-11eb-9d08-a9369ceebc99.png)

**Comment by SUMER9999dev** [comment]
уже готовое исправление аргументов:
https://github.com/WhiteApfel/pyQiwiP2P/pull/7

**Comment by WhiteApfel** [comment]
Готово 🚀

**Comment by SUMER9999dev** [comment]
@WhiteApfel у тебя есть дискорд?

**Comment by WhiteApfel** [comment]
Предлагаю закрыть обсудениеп под этим иссуесом и продолжить диалог в TG или по электронной почте 

[https://pypi.org/project/pyQiwiP2P/1.0a12/](https://pypi.org/project/pyQiwiP2P/1.0a12/)

Обновление пакета уже доступно через pip:
`python -m pip install -U pyqiwip2p`

**Comment by SUMER9999dev** [comment]
Окей, отправьте ваш TG и перейдём туда.
